#! /bin/sh

fwid=$(bspc query -N -n focused.automatic)
wid=$1
receptacle=$(bspc query -N -n ".leaf.!window.local"  | awk NR==1)

if bspc query -N -n "@/.!automatic" > /dev/null ; then
    echo "node=@/"
fi

if [ -n "$receptacle" ] > /dev/null ; then
    echo "node=$receptacle"
elif [ -n "$fwid" ] ; then
	wattr wh $fwid | {
		read width height
		if [ $width -gt $height ] ; then
			echo "split_dir=west"
		else
			echo "split_dir=south"
		fi
	}
fi

wmctrl -i -r "$wid" -b add,maximized_vert,maximized_horz &>/dev/null &

