#!/bin/sh

while true
do
    sleep 3
    acpi -b | awk -F'[,:%]' '{print $2, $3}' | {
        read -r status capacity
        if [ "$status" = Discharging ]; then
            if [ "$capacity" -eq 10 ]; then
                notify-send -u critical -a battery "Low battery" "Only 10% battery remaining\!"
            elif [ "$capacity" -lt 5 ]; then
                notify-send -u critical -a battery "Critical battery threshold" "System will be hibernated in 30 seconds\!"
                sleep 30
                systemctl hibernate
            fi
        fi
    }
done
