#!/usr/bin/sh

name=$(nmcli con show --active | awk '/vpn/{print $1}')

if (( ${#name} >= 20  ))
then
    name="${name[@]:0:17}..."
fi

if [ $name ]
then
    echo "%{T2}聯%{T-} $name"
else
    echo "%{T2}輦%{T-}"
fi

