#!/bin/sh

player_status=$(playerctl -p spotify status 2> /dev/null)

metadata=$(echo "$(playerctl -p spotify metadata artist 2> /dev/null) - $(playerctl -p spotify metadata title 2> /dev/null)" | awk -v len=85 '{ if (length($0) > len) print substr($0, 1, len-3) "..."; else print $0 }')

if [ "$player_status" = "Playing" ]; then
    echo "%{T2}%{T-} ${metadata}"
elif [ "$player_status" = "Paused" ]; then
    echo "%{T2}%{T1} ${metadata}" 
else
    echo ""
fi
