#!/usr/bin/sh

name=$(nmcli --get-values name,type,active connection | awk -F':' -v len=30 '/vpn:yes/{ if (length($1) > len) print substr($1, 1, len-3) "..."; else print $1 }')

if [ "$name" ]
then
    echo "%{T2}聯%{T-} $name"
else
    echo "%{T2}輦%{T-}"
fi

