#!/bin/sh

name=$(vpn get | awk -v len=30 '{ if (length($1) > len) print substr($1, 1, len-3) "..."; else print $1 }')

if [ "$name" ]
then
    echo "%{T2}聯%{T-} $name"
else
    echo "%{T2}輦%{T-}"
fi
