#!/bin/sh


TIMEOUT=5
LOCK=/tmp/vpn-lock


usage() { 
  echo -e "Usage: vpn { get | up | down }\n  up [id | uuid | path]\n  down\n  get"
  exit 1
}

list() {
  nmcli --get-values name,type,active connection | awk -F ':' '/:vpn:/{if ($3 == "yes") printf "*"; else printf " "; print $1}'
}

get() {
  nmcli --get-values name,type,active connection | awk -F ':' '/vpn:yes/{print $1}'
}


down() {
  case $1 in
    --temporarily|-t)
      connection=$(get)
      rm -f $LOCK
      nmcli connection down $connection
      sleep $TIMEOUT
      [ -f $LOCK ] || up $connection
      ;;
    *)
      touch $LOCK
      nmcli connection down $(get)
      ;;
  esac
}


up() {
  case $2 in
    --temporarily|-t)
      connection=$(get)
      rm -f $LOCK
      nmcli connection down $connection
      nmcli connection up $1
      sleep $TIMEOUT
      [ -f $LOCK ] || up $connection
      ;;
    *)
      touch $LOCK
      nmcli connection down $(get)
      nmcli connection up $1
      ;;
  esac
}


case $1 in
  list)
    list
    ;;
  get)
    get
    ;;
  up)
    up $2 $3
    ;;
  down)
    down $2
    ;;
  *)
    usage
    ;;
esac

