#!/bin/bash

# Map super keys to trigger when used alone
xcape -e 'Super_L=Super_L|Shift_L|space;Super_R=Super_R|Shift_R|z' &

# Touchapad gestures
fusuma &

# Polybar
polybar-launch &

# Clipboard manager
greenclip daemon &

# Compton
picom -b --xperimental-backends &

# Other
redshift &

# Battery daemon
battery-daemon &

