#!/bin/sh

# Export pywal colors
source "${HOME}/.cache/wal/colors.sh"

# Path for rules
RULES="${HOME}/.config/bspwm/rules"


## Gaps 
bspc config window_gap 10
bspc config top_padding 30
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0


## Various settings
bspc config gapless_monocle false
bspc config borderless_monocle true
bspc config single_monocle true
bspc config paddingless_monocle false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config honor_size_hints false 
bspc config focus_follows_pointer true
bspc config split_ratio 0.5


## Border and color settings
bspc config border_width 0


## Workspaces
bspc monitor -d DEV WEB DOC ART MEDIA REST GAME CHAT SYS


## Rules

# Source rules from separate files
source $RULES/apps
source $RULES/steam

# Source external rules
bspc config external_rules_command $RULES/spotify
bspc config external_rules_command $RULES/pseudo_automatic_mode

